INVALID_METHOD = 0

PROJECT_IRIS_SEGMENTATION = 1
VASIR_SEGMENTATION = 2

PROJECT_IRIS_NORMALIZATION = 1
RUBBERSHEET_NORMALIZATION = 2

GABOR_FILTERS_ENCODING = 1
LOG_GABOR_ENCODING = 2
ZCP_ENCODING = 3
ZAP_ENCODING = 4
FOURIER_ENCODING = 5

GABOR_FILTERS_ENCODING_STR = "2D Gabor filters"
LOG_GABOR_ENCODING_STR = "LoG Gabor filters"
ZCP_ENCODING_STR = "Zernike Circular Polynomials"
ZAP_ENCODING_STR = "Zernike Annular Polynomials"
FOURIER_ENCODING_STR = "Discrete Fourier Transform"

HAMMING_DISTANCE = 1
EUCLIDEAN_DISTANCE = 2

MIN_ANGULAR_RESOLUTION = 45
MAX_ANGULAR_RESOLUTION = 360


MIN_RADIAL_RESOLUTION = 8
MAX_RADIAL_RESOLUTION = 64

DEFAULT_ZERNIKE_ORDER = 16
DEFAULT_EPS_INT = 0.5
DEFAULT_EPS_EXT = 1.0
