# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/airs_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_airsWindow(object):
    def setupUi(self, airsWindow):
        airsWindow.setObjectName("airsWindow")
        airsWindow.resize(692, 718)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(airsWindow.sizePolicy().hasHeightForWidth())
        airsWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(airsWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.airsOptionsTabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.airsOptionsTabWidget.setObjectName("airsOptionsTabWidget")
        self.processingTab = QtWidgets.QWidget()
        self.processingTab.setObjectName("processingTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.processingTab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 1, 0, 1, 1)
        self.irisViewer = IrisViewerWidget(self.processingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irisViewer.sizePolicy().hasHeightForWidth())
        self.irisViewer.setSizePolicy(sizePolicy)
        self.irisViewer.setMinimumSize(QtCore.QSize(300, 200))
        self.irisViewer.setFocusPolicy(QtCore.Qt.NoFocus)
        self.irisViewer.setObjectName("irisViewer")
        self.gridLayout_8.addWidget(self.irisViewer, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 1, 2, 1, 1)
        self.irisImageLabel = QtWidgets.QLabel(self.processingTab)
        self.irisImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.irisImageLabel.setObjectName("irisImageLabel")
        self.gridLayout_8.addWidget(self.irisImageLabel, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.loadIrisButton = QtWidgets.QPushButton(self.processingTab)
        self.loadIrisButton.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadIrisButton.setFont(font)
        self.loadIrisButton.setObjectName("loadIrisButton")
        self.horizontalLayout.addWidget(self.loadIrisButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout_8.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_8, 0, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.normalizedIrisLabel = QtWidgets.QLabel(self.processingTab)
        self.normalizedIrisLabel.setObjectName("normalizedIrisLabel")
        self.verticalLayout_2.addWidget(self.normalizedIrisLabel)
        self.normIrisImageViewer = ImageViewerWidget(self.processingTab)
        self.normIrisImageViewer.setMinimumSize(QtCore.QSize(0, 0))
        self.normIrisImageViewer.setObjectName("normIrisImageViewer")
        self.verticalLayout_2.addWidget(self.normIrisImageViewer)
        self.heatmapLabel = QtWidgets.QLabel(self.processingTab)
        self.heatmapLabel.setObjectName("heatmapLabel")
        self.verticalLayout_2.addWidget(self.heatmapLabel)
        self.heatmapImageViewer = ImageViewerWidget(self.processingTab)
        self.heatmapImageViewer.setMinimumSize(QtCore.QSize(0, 0))
        self.heatmapImageViewer.setObjectName("heatmapImageViewer")
        self.verticalLayout_2.addWidget(self.heatmapImageViewer)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.segmentButton = QtWidgets.QPushButton(self.processingTab)
        self.segmentButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.segmentButton.setFont(font)
        self.segmentButton.setObjectName("segmentButton")
        self.gridLayout_3.addWidget(self.segmentButton, 1, 1, 1, 1)
        self.normalizeButton = QtWidgets.QPushButton(self.processingTab)
        self.normalizeButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.normalizeButton.setFont(font)
        self.normalizeButton.setObjectName("normalizeButton")
        self.gridLayout_3.addWidget(self.normalizeButton, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 1, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 2, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 2, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 6, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 3, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 3, 2, 1, 1)
        self.computeHeatmapButton = QtWidgets.QPushButton(self.processingTab)
        self.computeHeatmapButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.computeHeatmapButton.setFont(font)
        self.computeHeatmapButton.setObjectName("computeHeatmapButton")
        self.gridLayout_3.addWidget(self.computeHeatmapButton, 3, 1, 1, 1)
        self.encodeButton = QtWidgets.QPushButton(self.processingTab)
        self.encodeButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.encodeButton.setFont(font)
        self.encodeButton.setObjectName("encodeButton")
        self.gridLayout_3.addWidget(self.encodeButton, 5, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem14, 5, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 5, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 1, 1, 2)
        self.irisProcessingTabWidget = QtWidgets.QTabWidget(self.processingTab)
        self.irisProcessingTabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.irisProcessingTabWidget.setObjectName("irisProcessingTabWidget")
        self.irisSegmentationTab = QtWidgets.QWidget()
        self.irisSegmentationTab.setObjectName("irisSegmentationTab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.irisSegmentationTab)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pupilInfoGroupBox = QtWidgets.QGroupBox(self.irisSegmentationTab)
        self.pupilInfoGroupBox.setMinimumSize(QtCore.QSize(150, 0))
        self.pupilInfoGroupBox.setObjectName("pupilInfoGroupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.pupilInfoGroupBox)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pupilCenterAbscissaLabel = QtWidgets.QLabel(self.pupilInfoGroupBox)
        self.pupilCenterAbscissaLabel.setObjectName("pupilCenterAbscissaLabel")
        self.gridLayout_7.addWidget(self.pupilCenterAbscissaLabel, 0, 0, 1, 1)
        self.pupilCenterOrdinateLabel = QtWidgets.QLabel(self.pupilInfoGroupBox)
        self.pupilCenterOrdinateLabel.setObjectName("pupilCenterOrdinateLabel")
        self.gridLayout_7.addWidget(self.pupilCenterOrdinateLabel, 0, 1, 1, 1)
        self.pupilBorderAbscissaLabel = QtWidgets.QLabel(self.pupilInfoGroupBox)
        self.pupilBorderAbscissaLabel.setObjectName("pupilBorderAbscissaLabel")
        self.gridLayout_7.addWidget(self.pupilBorderAbscissaLabel, 0, 2, 1, 1)
        self.pupilBorderOrdinateLabel = QtWidgets.QLabel(self.pupilInfoGroupBox)
        self.pupilBorderOrdinateLabel.setObjectName("pupilBorderOrdinateLabel")
        self.gridLayout_7.addWidget(self.pupilBorderOrdinateLabel, 0, 3, 1, 1)
        self.pupilRadiusLabel = QtWidgets.QLabel(self.pupilInfoGroupBox)
        self.pupilRadiusLabel.setObjectName("pupilRadiusLabel")
        self.gridLayout_7.addWidget(self.pupilRadiusLabel, 0, 4, 1, 1)
        self.pupilCenterAbscissaSpinBox = QtWidgets.QSpinBox(self.pupilInfoGroupBox)
        self.pupilCenterAbscissaSpinBox.setEnabled(False)
        self.pupilCenterAbscissaSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pupilCenterAbscissaSpinBox.setMaximum(500)
        self.pupilCenterAbscissaSpinBox.setObjectName("pupilCenterAbscissaSpinBox")
        self.gridLayout_7.addWidget(self.pupilCenterAbscissaSpinBox, 1, 0, 1, 1)
        self.pupilCenterOrdinateSpinBox = QtWidgets.QSpinBox(self.pupilInfoGroupBox)
        self.pupilCenterOrdinateSpinBox.setEnabled(False)
        self.pupilCenterOrdinateSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pupilCenterOrdinateSpinBox.setMaximum(500)
        self.pupilCenterOrdinateSpinBox.setObjectName("pupilCenterOrdinateSpinBox")
        self.gridLayout_7.addWidget(self.pupilCenterOrdinateSpinBox, 1, 1, 1, 1)
        self.pupilBorderAbscissaSpinBox = QtWidgets.QSpinBox(self.pupilInfoGroupBox)
        self.pupilBorderAbscissaSpinBox.setEnabled(False)
        self.pupilBorderAbscissaSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pupilBorderAbscissaSpinBox.setMaximum(500)
        self.pupilBorderAbscissaSpinBox.setObjectName("pupilBorderAbscissaSpinBox")
        self.gridLayout_7.addWidget(self.pupilBorderAbscissaSpinBox, 1, 2, 1, 1)
        self.pupilBorderOrdinateSpinBox = QtWidgets.QSpinBox(self.pupilInfoGroupBox)
        self.pupilBorderOrdinateSpinBox.setEnabled(False)
        self.pupilBorderOrdinateSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pupilBorderOrdinateSpinBox.setMaximum(500)
        self.pupilBorderOrdinateSpinBox.setObjectName("pupilBorderOrdinateSpinBox")
        self.gridLayout_7.addWidget(self.pupilBorderOrdinateSpinBox, 1, 3, 1, 1)
        self.pupilRadiusSpinBox = QtWidgets.QSpinBox(self.pupilInfoGroupBox)
        self.pupilRadiusSpinBox.setEnabled(False)
        self.pupilRadiusSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pupilRadiusSpinBox.setReadOnly(True)
        self.pupilRadiusSpinBox.setMaximum(500)
        self.pupilRadiusSpinBox.setObjectName("pupilRadiusSpinBox")
        self.gridLayout_7.addWidget(self.pupilRadiusSpinBox, 1, 4, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.pupilInfoGroupBox, 0, 0, 1, 1)
        self.irisInfoGroupBox = QtWidgets.QGroupBox(self.irisSegmentationTab)
        self.irisInfoGroupBox.setMinimumSize(QtCore.QSize(150, 0))
        self.irisInfoGroupBox.setObjectName("irisInfoGroupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.irisInfoGroupBox)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.irisCenterAbscissaLabel = QtWidgets.QLabel(self.irisInfoGroupBox)
        self.irisCenterAbscissaLabel.setObjectName("irisCenterAbscissaLabel")
        self.gridLayout_13.addWidget(self.irisCenterAbscissaLabel, 0, 0, 1, 1)
        self.irisCenterOrdinateLabel = QtWidgets.QLabel(self.irisInfoGroupBox)
        self.irisCenterOrdinateLabel.setObjectName("irisCenterOrdinateLabel")
        self.gridLayout_13.addWidget(self.irisCenterOrdinateLabel, 0, 1, 1, 1)
        self.irisBorderAbscissaLabel = QtWidgets.QLabel(self.irisInfoGroupBox)
        self.irisBorderAbscissaLabel.setObjectName("irisBorderAbscissaLabel")
        self.gridLayout_13.addWidget(self.irisBorderAbscissaLabel, 0, 2, 1, 1)
        self.irisBorderOrdinateLabel = QtWidgets.QLabel(self.irisInfoGroupBox)
        self.irisBorderOrdinateLabel.setObjectName("irisBorderOrdinateLabel")
        self.gridLayout_13.addWidget(self.irisBorderOrdinateLabel, 0, 3, 1, 1)
        self.irisRadiusLabel = QtWidgets.QLabel(self.irisInfoGroupBox)
        self.irisRadiusLabel.setObjectName("irisRadiusLabel")
        self.gridLayout_13.addWidget(self.irisRadiusLabel, 0, 4, 1, 1)
        self.irisCenterAbscissaSpinBox = QtWidgets.QSpinBox(self.irisInfoGroupBox)
        self.irisCenterAbscissaSpinBox.setEnabled(False)
        self.irisCenterAbscissaSpinBox.setMaximum(500)
        self.irisCenterAbscissaSpinBox.setObjectName("irisCenterAbscissaSpinBox")
        self.gridLayout_13.addWidget(self.irisCenterAbscissaSpinBox, 1, 0, 1, 1)
        self.irisCenterOrdinateSpinBox = QtWidgets.QSpinBox(self.irisInfoGroupBox)
        self.irisCenterOrdinateSpinBox.setEnabled(False)
        self.irisCenterOrdinateSpinBox.setMaximum(500)
        self.irisCenterOrdinateSpinBox.setObjectName("irisCenterOrdinateSpinBox")
        self.gridLayout_13.addWidget(self.irisCenterOrdinateSpinBox, 1, 1, 1, 1)
        self.irisBorderAbscissaSpinBox = QtWidgets.QSpinBox(self.irisInfoGroupBox)
        self.irisBorderAbscissaSpinBox.setEnabled(False)
        self.irisBorderAbscissaSpinBox.setMaximum(500)
        self.irisBorderAbscissaSpinBox.setObjectName("irisBorderAbscissaSpinBox")
        self.gridLayout_13.addWidget(self.irisBorderAbscissaSpinBox, 1, 2, 1, 1)
        self.irisBorderOrdinateSpinBox = QtWidgets.QSpinBox(self.irisInfoGroupBox)
        self.irisBorderOrdinateSpinBox.setEnabled(False)
        self.irisBorderOrdinateSpinBox.setMaximum(500)
        self.irisBorderOrdinateSpinBox.setObjectName("irisBorderOrdinateSpinBox")
        self.gridLayout_13.addWidget(self.irisBorderOrdinateSpinBox, 1, 3, 1, 1)
        self.irisRadiusSpinBox = QtWidgets.QSpinBox(self.irisInfoGroupBox)
        self.irisRadiusSpinBox.setEnabled(False)
        self.irisRadiusSpinBox.setReadOnly(True)
        self.irisRadiusSpinBox.setMaximum(500)
        self.irisRadiusSpinBox.setObjectName("irisRadiusSpinBox")
        self.gridLayout_13.addWidget(self.irisRadiusSpinBox, 1, 4, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.irisInfoGroupBox, 1, 0, 1, 1)
        self.segMethodGroupBox = QtWidgets.QGroupBox(self.irisSegmentationTab)
        self.segMethodGroupBox.setObjectName("segMethodGroupBox")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.segMethodGroupBox)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.projIrisRadioButton = QtWidgets.QRadioButton(self.segMethodGroupBox)
        self.projIrisRadioButton.setChecked(True)
        self.projIrisRadioButton.setObjectName("projIrisRadioButton")
        self.gridLayout_16.addWidget(self.projIrisRadioButton, 0, 0, 1, 1)
        self.vasirRadioButton = QtWidgets.QRadioButton(self.segMethodGroupBox)
        self.vasirRadioButton.setEnabled(False)
        self.vasirRadioButton.setChecked(False)
        self.vasirRadioButton.setObjectName("vasirRadioButton")
        self.gridLayout_16.addWidget(self.vasirRadioButton, 1, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem16, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem17, 1, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem18, 2, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.segMethodGroupBox, 2, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.irisProcessingTabWidget.addTab(self.irisSegmentationTab, "")
        self.irisNormalizationTab = QtWidgets.QWidget()
        self.irisNormalizationTab.setObjectName("irisNormalizationTab")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.irisNormalizationTab)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.normTechniqueGroupBox = QtWidgets.QGroupBox(self.irisNormalizationTab)
        self.normTechniqueGroupBox.setObjectName("normTechniqueGroupBox")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.normTechniqueGroupBox)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.concentricRadioButton = QtWidgets.QRadioButton(self.normTechniqueGroupBox)
        self.concentricRadioButton.setChecked(False)
        self.concentricRadioButton.setObjectName("concentricRadioButton")
        self.gridLayout.addWidget(self.concentricRadioButton, 0, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 0, 1, 1, 1)
        self.nonconcentricRadioButton = QtWidgets.QRadioButton(self.normTechniqueGroupBox)
        self.nonconcentricRadioButton.setChecked(True)
        self.nonconcentricRadioButton.setObjectName("nonconcentricRadioButton")
        self.gridLayout.addWidget(self.nonconcentricRadioButton, 1, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem20, 1, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem21, 2, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.normTechniqueGroupBox, 0, 0, 1, 1)
        self.dataMappingGroupBox = QtWidgets.QGroupBox(self.irisNormalizationTab)
        self.dataMappingGroupBox.setObjectName("dataMappingGroupBox")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.dataMappingGroupBox)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.angularResolutionLabel = QtWidgets.QLabel(self.dataMappingGroupBox)
        self.angularResolutionLabel.setObjectName("angularResolutionLabel")
        self.gridLayout_6.addWidget(self.angularResolutionLabel, 0, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem22, 0, 2, 1, 1)
        self.templateWidthSpinBox = QtWidgets.QSpinBox(self.dataMappingGroupBox)
        self.templateWidthSpinBox.setMaximum(360)
        self.templateWidthSpinBox.setProperty("value", 180)
        self.templateWidthSpinBox.setObjectName("templateWidthSpinBox")
        self.gridLayout_6.addWidget(self.templateWidthSpinBox, 1, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem23, 1, 2, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(28, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem24, 2, 0, 1, 1)
        self.radialResolutionLabel = QtWidgets.QLabel(self.dataMappingGroupBox)
        self.radialResolutionLabel.setObjectName("radialResolutionLabel")
        self.gridLayout_6.addWidget(self.radialResolutionLabel, 0, 1, 1, 1)
        self.templateHeightSpinBox = QtWidgets.QSpinBox(self.dataMappingGroupBox)
        self.templateHeightSpinBox.setMaximum(100)
        self.templateHeightSpinBox.setProperty("value", 32)
        self.templateHeightSpinBox.setObjectName("templateHeightSpinBox")
        self.gridLayout_6.addWidget(self.templateHeightSpinBox, 1, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.dataMappingGroupBox, 1, 0, 1, 1)
        self.noiseInfoGroupBox = QtWidgets.QGroupBox(self.irisNormalizationTab)
        self.noiseInfoGroupBox.setObjectName("noiseInfoGroupBox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.noiseInfoGroupBox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.showMaskCheckBox = QtWidgets.QCheckBox(self.noiseInfoGroupBox)
        self.showMaskCheckBox.setChecked(True)
        self.showMaskCheckBox.setObjectName("showMaskCheckBox")
        self.gridLayout_14.addWidget(self.showMaskCheckBox, 0, 0, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem25, 0, 1, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem26, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.noiseInfoGroupBox, 2, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.irisProcessingTabWidget.addTab(self.irisNormalizationTab, "")
        self.irisEncodingTab = QtWidgets.QWidget()
        self.irisEncodingTab.setObjectName("irisEncodingTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.irisEncodingTab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.encodingTechniqueGroupBox = QtWidgets.QGroupBox(self.irisEncodingTab)
        self.encodingTechniqueGroupBox.setObjectName("encodingTechniqueGroupBox")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.encodingTechniqueGroupBox)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.daugmanRadioButton = QtWidgets.QRadioButton(self.encodingTechniqueGroupBox)
        self.daugmanRadioButton.setChecked(True)
        self.daugmanRadioButton.setObjectName("daugmanRadioButton")
        self.gridLayout_4.addWidget(self.daugmanRadioButton, 0, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem27, 0, 1, 1, 1)
        self.masekRadioButton = QtWidgets.QRadioButton(self.encodingTechniqueGroupBox)
        self.masekRadioButton.setObjectName("masekRadioButton")
        self.gridLayout_4.addWidget(self.masekRadioButton, 1, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem28, 1, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem29, 5, 0, 1, 1)
        self.zernikeCircularRadioButton = QtWidgets.QRadioButton(self.encodingTechniqueGroupBox)
        self.zernikeCircularRadioButton.setEnabled(False)
        self.zernikeCircularRadioButton.setObjectName("zernikeCircularRadioButton")
        self.gridLayout_4.addWidget(self.zernikeCircularRadioButton, 2, 0, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem30, 2, 1, 1, 1)
        self.zernikeAnnularRadioButton = QtWidgets.QRadioButton(self.encodingTechniqueGroupBox)
        self.zernikeAnnularRadioButton.setObjectName("zernikeAnnularRadioButton")
        self.gridLayout_4.addWidget(self.zernikeAnnularRadioButton, 3, 0, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem31, 3, 1, 1, 1)
        self.fourierRadioButton = QtWidgets.QRadioButton(self.encodingTechniqueGroupBox)
        self.fourierRadioButton.setEnabled(False)
        self.fourierRadioButton.setObjectName("fourierRadioButton")
        self.gridLayout_4.addWidget(self.fourierRadioButton, 4, 0, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem32, 4, 1, 1, 1)
        self.horizontalLayout_14.addLayout(self.gridLayout_4)
        self.horizontalLayout_2.addWidget(self.encodingTechniqueGroupBox)
        self.irisProcessingTabWidget.addTab(self.irisEncodingTab, "")
        self.outputTab = QtWidgets.QWidget()
        self.outputTab.setObjectName("outputTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.outputTab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.outputTextEdit = QtWidgets.QTextEdit(self.outputTab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.outputTextEdit.setFont(font)
        self.outputTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.outputTextEdit.setReadOnly(True)
        self.outputTextEdit.setAcceptRichText(False)
        self.outputTextEdit.setObjectName("outputTextEdit")
        self.verticalLayout_6.addWidget(self.outputTextEdit)
        self.irisProcessingTabWidget.addTab(self.outputTab, "")
        self.gridLayout_5.addWidget(self.irisProcessingTabWidget, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.airsOptionsTabWidget.addTab(self.processingTab, "")
        self.matchTab = QtWidgets.QWidget()
        self.matchTab.setObjectName("matchTab")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.matchTab)
        self.gridLayout_31.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.algorithmSelectionGroupBox = QtWidgets.QGroupBox(self.matchTab)
        self.algorithmSelectionGroupBox.setObjectName("algorithmSelectionGroupBox")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.algorithmSelectionGroupBox)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.segmentationGroupBox = QtWidgets.QGroupBox(self.algorithmSelectionGroupBox)
        self.segmentationGroupBox.setObjectName("segmentationGroupBox")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.segmentationGroupBox)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.projectIrisSegmRadioButton = QtWidgets.QRadioButton(self.segmentationGroupBox)
        self.projectIrisSegmRadioButton.setChecked(True)
        self.projectIrisSegmRadioButton.setObjectName("projectIrisSegmRadioButton")
        self.gridLayout_22.addWidget(self.projectIrisSegmRadioButton, 0, 0, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem33, 0, 1, 1, 1)
        self.vasirSegmRadioButton = QtWidgets.QRadioButton(self.segmentationGroupBox)
        self.vasirSegmRadioButton.setEnabled(False)
        self.vasirSegmRadioButton.setObjectName("vasirSegmRadioButton")
        self.gridLayout_22.addWidget(self.vasirSegmRadioButton, 1, 0, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem34, 1, 1, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem35, 2, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.gridLayout_28.addWidget(self.segmentationGroupBox, 0, 0, 1, 1)
        self.encodingGroupBox = QtWidgets.QGroupBox(self.algorithmSelectionGroupBox)
        self.encodingGroupBox.setObjectName("encodingGroupBox")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.encodingGroupBox)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.projectIrisEncRadioButton = QtWidgets.QRadioButton(self.encodingGroupBox)
        self.projectIrisEncRadioButton.setChecked(True)
        self.projectIrisEncRadioButton.setObjectName("projectIrisEncRadioButton")
        self.gridLayout_26.addWidget(self.projectIrisEncRadioButton, 0, 0, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem36, 0, 2, 1, 1)
        self.vasirEncRadioButton = QtWidgets.QRadioButton(self.encodingGroupBox)
        self.vasirEncRadioButton.setEnabled(False)
        self.vasirEncRadioButton.setObjectName("vasirEncRadioButton")
        self.gridLayout_26.addWidget(self.vasirEncRadioButton, 1, 0, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem37, 1, 2, 1, 1)
        self.zcpEncRadioButton = QtWidgets.QRadioButton(self.encodingGroupBox)
        self.zcpEncRadioButton.setEnabled(False)
        self.zcpEncRadioButton.setObjectName("zcpEncRadioButton")
        self.gridLayout_26.addWidget(self.zcpEncRadioButton, 0, 1, 1, 1)
        self.zapEncRadioButton = QtWidgets.QRadioButton(self.encodingGroupBox)
        self.zapEncRadioButton.setObjectName("zapEncRadioButton")
        self.gridLayout_26.addWidget(self.zapEncRadioButton, 1, 1, 1, 1)
        self.fourierEncRadioButton = QtWidgets.QRadioButton(self.encodingGroupBox)
        self.fourierEncRadioButton.setEnabled(False)
        self.fourierEncRadioButton.setObjectName("fourierEncRadioButton")
        self.gridLayout_26.addWidget(self.fourierEncRadioButton, 2, 0, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem38, 2, 1, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem39, 2, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.encodingGroupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_26.addWidget(self.line, 3, 0, 1, 3)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem40, 4, 1, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem41, 4, 2, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem42, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.matchThresholdLabel = QtWidgets.QLabel(self.encodingGroupBox)
        self.matchThresholdLabel.setObjectName("matchThresholdLabel")
        self.horizontalLayout_3.addWidget(self.matchThresholdLabel)
        self.matchThresholdSpinBox = QtWidgets.QDoubleSpinBox(self.encodingGroupBox)
        self.matchThresholdSpinBox.setSingleStep(0.01)
        self.matchThresholdSpinBox.setProperty("value", 0.0)
        self.matchThresholdSpinBox.setObjectName("matchThresholdSpinBox")
        self.horizontalLayout_3.addWidget(self.matchThresholdSpinBox)
        self.gridLayout_26.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_26, 0, 0, 1, 1)
        self.gridLayout_28.addWidget(self.encodingGroupBox, 0, 2, 1, 1)
        self.normalizationGroupBox = QtWidgets.QGroupBox(self.algorithmSelectionGroupBox)
        self.normalizationGroupBox.setObjectName("normalizationGroupBox")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.normalizationGroupBox)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.projectIrisNormRadioButton = QtWidgets.QRadioButton(self.normalizationGroupBox)
        self.projectIrisNormRadioButton.setChecked(False)
        self.projectIrisNormRadioButton.setObjectName("projectIrisNormRadioButton")
        self.gridLayout_24.addWidget(self.projectIrisNormRadioButton, 0, 0, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem43, 0, 1, 1, 1)
        self.vasirNormRadioButton = QtWidgets.QRadioButton(self.normalizationGroupBox)
        self.vasirNormRadioButton.setEnabled(True)
        self.vasirNormRadioButton.setChecked(True)
        self.vasirNormRadioButton.setObjectName("vasirNormRadioButton")
        self.gridLayout_24.addWidget(self.vasirNormRadioButton, 1, 0, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem44, 1, 1, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_24.addItem(spacerItem45, 2, 0, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_24, 0, 0, 1, 1)
        self.gridLayout_28.addWidget(self.normalizationGroupBox, 0, 1, 1, 1)
        self.gridLayout_29.addLayout(self.gridLayout_28, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.algorithmSelectionGroupBox, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem46)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem47)
        self.originalIrisLabel = QtWidgets.QLabel(self.matchTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.originalIrisLabel.setFont(font)
        self.originalIrisLabel.setObjectName("originalIrisLabel")
        self.horizontalLayout_4.addWidget(self.originalIrisLabel)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem48)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.origIrisImageViewer = ImageViewerWidget(self.matchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.origIrisImageViewer.sizePolicy().hasHeightForWidth())
        self.origIrisImageViewer.setSizePolicy(sizePolicy)
        self.origIrisImageViewer.setMinimumSize(QtCore.QSize(300, 200))
        self.origIrisImageViewer.setObjectName("origIrisImageViewer")
        self.verticalLayout_7.addWidget(self.origIrisImageViewer)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem49)
        self.originalLoadIrisButton = QtWidgets.QPushButton(self.matchTab)
        self.originalLoadIrisButton.setMinimumSize(QtCore.QSize(0, 0))
        self.originalLoadIrisButton.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.originalLoadIrisButton.setFont(font)
        self.originalLoadIrisButton.setObjectName("originalLoadIrisButton")
        self.horizontalLayout_5.addWidget(self.originalLoadIrisButton)
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem50)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        spacerItem51 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem51)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem52)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem53)
        self.queryIrisLabel = QtWidgets.QLabel(self.matchTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.queryIrisLabel.setFont(font)
        self.queryIrisLabel.setObjectName("queryIrisLabel")
        self.horizontalLayout_7.addWidget(self.queryIrisLabel)
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem54)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.queryIrisImageViewer = ImageViewerWidget(self.matchTab)
        self.queryIrisImageViewer.setMinimumSize(QtCore.QSize(300, 200))
        self.queryIrisImageViewer.setObjectName("queryIrisImageViewer")
        self.verticalLayout_9.addWidget(self.queryIrisImageViewer)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem55 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem55)
        self.queryLoadIrisButton = QtWidgets.QPushButton(self.matchTab)
        self.queryLoadIrisButton.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.queryLoadIrisButton.setFont(font)
        self.queryLoadIrisButton.setObjectName("queryLoadIrisButton")
        self.horizontalLayout_8.addWidget(self.queryLoadIrisButton)
        spacerItem56 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem56)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        spacerItem57 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem57)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        spacerItem58 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem58)
        self.gridLayout_30.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem59 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem59)
        self.goButton = QtWidgets.QPushButton(self.matchTab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.goButton.setFont(font)
        self.goButton.setObjectName("goButton")
        self.horizontalLayout_6.addWidget(self.goButton)
        spacerItem60 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem60)
        self.gridLayout_30.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        spacerItem61 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_30.addItem(spacerItem61, 4, 0, 1, 1)
        self.resultLabel = QtWidgets.QLabel(self.matchTab)
        self.resultLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.resultLabel.setFont(font)
        self.resultLabel.setStyleSheet("")
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.gridLayout_30.addWidget(self.resultLabel, 5, 0, 1, 1)
        spacerItem62 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_30.addItem(spacerItem62, 3, 0, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_30, 0, 0, 1, 1)
        self.airsOptionsTabWidget.addTab(self.matchTab, "")
        self.testsTab = QtWidgets.QWidget()
        self.testsTab.setObjectName("testsTab")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.testsTab)
        self.gridLayout_42.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.gridLayout_41 = QtWidgets.QGridLayout()
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.encMethodGroupBox = QtWidgets.QGroupBox(self.testsTab)
        self.encMethodGroupBox.setObjectName("encMethodGroupBox")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.encMethodGroupBox)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.gaborEncRadioButton = QtWidgets.QRadioButton(self.encMethodGroupBox)
        self.gaborEncRadioButton.setChecked(True)
        self.gaborEncRadioButton.setObjectName("gaborEncRadioButton")
        self.gridLayout_32.addWidget(self.gaborEncRadioButton, 0, 0, 1, 1)
        self.logGaborEncRadioButton = QtWidgets.QRadioButton(self.encMethodGroupBox)
        self.logGaborEncRadioButton.setObjectName("logGaborEncRadioButton")
        self.gridLayout_32.addWidget(self.logGaborEncRadioButton, 2, 0, 1, 1)
        self.fourEncRadioButton = QtWidgets.QRadioButton(self.encMethodGroupBox)
        self.fourEncRadioButton.setEnabled(False)
        self.fourEncRadioButton.setObjectName("fourEncRadioButton")
        self.gridLayout_32.addWidget(self.fourEncRadioButton, 8, 0, 1, 1)
        spacerItem63 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem63, 8, 2, 1, 1)
        spacerItem64 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_32.addItem(spacerItem64, 9, 0, 1, 1)
        spacerItem65 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_32.addItem(spacerItem65, 9, 2, 1, 1)
        self.zcpRadioButton = QtWidgets.QRadioButton(self.encMethodGroupBox)
        self.zcpRadioButton.setEnabled(False)
        self.zcpRadioButton.setObjectName("zcpRadioButton")
        self.gridLayout_32.addWidget(self.zcpRadioButton, 4, 0, 1, 1)
        self.zapRadioButton = QtWidgets.QRadioButton(self.encMethodGroupBox)
        self.zapRadioButton.setObjectName("zapRadioButton")
        self.gridLayout_32.addWidget(self.zapRadioButton, 6, 0, 1, 1)
        spacerItem66 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem66, 4, 2, 1, 1)
        spacerItem67 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem67, 2, 2, 1, 1)
        spacerItem68 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem68, 0, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.encMethodGroupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_32.addWidget(self.line_4, 1, 0, 1, 3)
        self.line_5 = QtWidgets.QFrame(self.encMethodGroupBox)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_32.addWidget(self.line_5, 3, 0, 1, 3)
        self.line_6 = QtWidgets.QFrame(self.encMethodGroupBox)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_32.addWidget(self.line_6, 5, 0, 1, 3)
        self.line_7 = QtWidgets.QFrame(self.encMethodGroupBox)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_32.addWidget(self.line_7, 7, 0, 1, 3)
        spacerItem69 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem69, 0, 1, 1, 1)
        spacerItem70 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem70, 2, 1, 1, 1)
        spacerItem71 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem71, 4, 1, 1, 1)
        spacerItem72 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem72, 8, 1, 1, 1)
        self.kComboBox = QtWidgets.QComboBox(self.encMethodGroupBox)
        self.kComboBox.setEnabled(False)
        self.kComboBox.setEditable(False)
        self.kComboBox.setObjectName("kComboBox")
        self.kComboBox.addItem("")
        self.kComboBox.addItem("")
        self.kComboBox.addItem("")
        self.gridLayout_32.addWidget(self.kComboBox, 6, 2, 1, 1)
        self.kLabel = QtWidgets.QLabel(self.encMethodGroupBox)
        self.kLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kLabel.setObjectName("kLabel")
        self.gridLayout_32.addWidget(self.kLabel, 6, 1, 1, 1)
        self.gridLayout_33.addLayout(self.gridLayout_32, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.encMethodGroupBox, 0, 0, 1, 1)
        self.testKindGroupBox = QtWidgets.QGroupBox(self.testsTab)
        self.testKindGroupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.testKindGroupBox.setObjectName("testKindGroupBox")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.testKindGroupBox)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.verificationRadioButton = QtWidgets.QRadioButton(self.testKindGroupBox)
        self.verificationRadioButton.setChecked(True)
        self.verificationRadioButton.setObjectName("verificationRadioButton")
        self.gridLayout_34.addWidget(self.verificationRadioButton, 0, 0, 1, 1)
        spacerItem73 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem73, 0, 1, 1, 2)
        self.identificationRadioButton = QtWidgets.QRadioButton(self.testKindGroupBox)
        self.identificationRadioButton.setObjectName("identificationRadioButton")
        self.gridLayout_34.addWidget(self.identificationRadioButton, 1, 0, 1, 1)
        spacerItem74 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem74, 1, 1, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.testKindGroupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_34.addWidget(self.line_3, 2, 0, 1, 3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.thresholdLabel = QtWidgets.QLabel(self.testKindGroupBox)
        self.thresholdLabel.setObjectName("thresholdLabel")
        self.horizontalLayout_10.addWidget(self.thresholdLabel)
        self.thresholdSpinBox = QtWidgets.QDoubleSpinBox(self.testKindGroupBox)
        self.thresholdSpinBox.setDecimals(2)
        self.thresholdSpinBox.setMaximum(100.0)
        self.thresholdSpinBox.setSingleStep(0.01)
        self.thresholdSpinBox.setObjectName("thresholdSpinBox")
        self.horizontalLayout_10.addWidget(self.thresholdSpinBox)
        self.gridLayout_34.addLayout(self.horizontalLayout_10, 3, 0, 1, 2)
        spacerItem75 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem75, 3, 2, 1, 1)
        spacerItem76 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_34.addItem(spacerItem76, 4, 0, 1, 1)
        self.gridLayout_35.addLayout(self.gridLayout_34, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.testKindGroupBox, 0, 1, 1, 1)
        self.databaseGroupBox = QtWidgets.QGroupBox(self.testsTab)
        self.databaseGroupBox.setObjectName("databaseGroupBox")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.databaseGroupBox)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.upolRadioButton = QtWidgets.QRadioButton(self.databaseGroupBox)
        self.upolRadioButton.setChecked(True)
        self.upolRadioButton.setObjectName("upolRadioButton")
        self.gridLayout_36.addWidget(self.upolRadioButton, 0, 0, 1, 1)
        spacerItem77 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem77, 0, 1, 1, 1)
        self.casia1RadioButton = QtWidgets.QRadioButton(self.databaseGroupBox)
        self.casia1RadioButton.setEnabled(False)
        self.casia1RadioButton.setObjectName("casia1RadioButton")
        self.gridLayout_36.addWidget(self.casia1RadioButton, 1, 0, 1, 1)
        spacerItem78 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem78, 1, 1, 1, 1)
        self.mmuRadioButton = QtWidgets.QRadioButton(self.databaseGroupBox)
        self.mmuRadioButton.setEnabled(False)
        self.mmuRadioButton.setObjectName("mmuRadioButton")
        self.gridLayout_36.addWidget(self.mmuRadioButton, 2, 0, 1, 1)
        spacerItem79 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem79, 2, 1, 1, 1)
        spacerItem80 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_36.addItem(spacerItem80, 6, 0, 1, 1)
        spacerItem81 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem81, 3, 1, 1, 1)
        self.ubirisRadioButton = QtWidgets.QRadioButton(self.databaseGroupBox)
        self.ubirisRadioButton.setEnabled(False)
        self.ubirisRadioButton.setObjectName("ubirisRadioButton")
        self.gridLayout_36.addWidget(self.ubirisRadioButton, 3, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.databaseGroupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_36.addWidget(self.line_2, 4, 0, 1, 2)
        self.useMaskCheckBox = QtWidgets.QCheckBox(self.databaseGroupBox)
        self.useMaskCheckBox.setEnabled(False)
        self.useMaskCheckBox.setObjectName("useMaskCheckBox")
        self.gridLayout_36.addWidget(self.useMaskCheckBox, 5, 0, 1, 1)
        spacerItem82 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem82, 5, 1, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_36, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.databaseGroupBox, 0, 2, 1, 1)
        self.gridLayout_41.addLayout(self.gridLayout_38, 0, 0, 1, 1)
        self.gridLayout_39 = QtWidgets.QGridLayout()
        self.gridLayout_39.setObjectName("gridLayout_39")
        spacerItem83 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_39.addItem(spacerItem83, 0, 0, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.testsTab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.gridLayout_39.addWidget(self.runButton, 0, 1, 1, 1)
        spacerItem84 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_39.addItem(spacerItem84, 0, 3, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.testsTab)
        self.stopButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_39.addWidget(self.stopButton, 0, 2, 1, 1)
        self.gridLayout_41.addLayout(self.gridLayout_39, 1, 0, 1, 1)
        self.resultsGroupBox = QtWidgets.QGroupBox(self.testsTab)
        self.resultsGroupBox.setObjectName("resultsGroupBox")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.resultsGroupBox)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.resultsTextEdit = QtWidgets.QTextEdit(self.resultsGroupBox)
        self.resultsTextEdit.setMinimumSize(QtCore.QSize(0, 350))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.resultsTextEdit.setFont(font)
        self.resultsTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.resultsTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.resultsTextEdit.setReadOnly(True)
        self.resultsTextEdit.setOverwriteMode(False)
        self.resultsTextEdit.setAcceptRichText(False)
        self.resultsTextEdit.setObjectName("resultsTextEdit")
        self.gridLayout_40.addWidget(self.resultsTextEdit, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.resultsGroupBox, 2, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_41, 0, 0, 1, 1)
        self.airsOptionsTabWidget.addTab(self.testsTab, "")
        self.gridLayout_2.addWidget(self.airsOptionsTabWidget, 0, 0, 1, 1)
        airsWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(airsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAdvanced = QtWidgets.QMenu(self.menubar)
        self.menuAdvanced.setObjectName("menuAdvanced")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        airsWindow.setMenuBar(self.menubar)
        self.actionQuit = QtWidgets.QAction(airsWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionConfiguration = QtWidgets.QAction(airsWindow)
        self.actionConfiguration.setObjectName("actionConfiguration")
        self.actionAbout = QtWidgets.QAction(airsWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(airsWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuFile.addAction(self.actionQuit)
        self.menuAdvanced.addAction(self.actionConfiguration)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAdvanced.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(airsWindow)
        self.airsOptionsTabWidget.setCurrentIndex(0)
        self.irisProcessingTabWidget.setCurrentIndex(0)
        self.kComboBox.setCurrentIndex(0)
        self.actionAbout.triggered.connect(airsWindow.onActionAboutTriggered)
        self.actionQuit.triggered.connect(airsWindow.onActionQuitTriggered)
        self.actionHelp.triggered.connect(airsWindow.onActionHelpTriggered)
        self.actionConfiguration.triggered.connect(airsWindow.onActionConfigurationTriggered)
        self.loadIrisButton.clicked.connect(airsWindow.onLoadIrisButtonClicked)
        self.originalLoadIrisButton.clicked.connect(airsWindow.onOriginalLoadIrisButtonClicked)
        self.queryLoadIrisButton.clicked.connect(airsWindow.onQueryLoadIrisButtonClicked)
        self.goButton.clicked.connect(airsWindow.onGoButtonClicked)
        self.irisViewer.pupilDetected.connect(airsWindow.onPupilDetected)
        self.irisViewer.irisDetected.connect(airsWindow.onIrisDetected)
        self.irisViewer.upperEyelidDetected.connect(airsWindow.onUpperEyelidDetected)
        self.irisViewer.lowerEyelidDetected.connect(airsWindow.onLowerEyelidDetected)
        self.irisViewer.irisSegmented.connect(airsWindow.onIrisSegmented)
        self.irisViewer.pupilCenterChanged.connect(airsWindow.onPupilCenterChanged)
        self.irisViewer.pupilBorderChanged.connect(airsWindow.onPupilBorderChanged)
        self.irisViewer.irisCenterChanged.connect(airsWindow.onIrisCenterChanged)
        self.irisViewer.irisBorderChanged.connect(airsWindow.onIrisBorderChanged)
        self.irisViewer.viewerReset.connect(airsWindow.onIrisViewerReset)
        self.pupilCenterAbscissaSpinBox.valueChanged['int'].connect(airsWindow.onPupilCenterAbscissaSpinBoxValueChanged)
        self.pupilCenterOrdinateSpinBox.valueChanged['int'].connect(airsWindow.onPupilCenterOrdinateSpinBoxValueChanged)
        self.irisCenterAbscissaSpinBox.valueChanged['int'].connect(airsWindow.onIrisCenterAbscissaSpinBoxValueChanged)
        self.irisCenterOrdinateSpinBox.valueChanged['int'].connect(airsWindow.onIrisCenterOrdinateSpinBoxValueChanged)
        self.pupilBorderAbscissaSpinBox.valueChanged['int'].connect(airsWindow.onPupilBorderAbscissaSpinBoxValueChanged)
        self.pupilBorderOrdinateSpinBox.valueChanged['int'].connect(airsWindow.onPupilBorderOrdinateSpinBoxValueChanged)
        self.irisBorderAbscissaSpinBox.valueChanged['int'].connect(airsWindow.onIrisBorderAbscissaSpinBoxValueChanged)
        self.irisBorderOrdinateSpinBox.valueChanged['int'].connect(airsWindow.onIrisBorderOrdinateSpinBoxValueChanged)
        self.irisViewer.pupilCenterSet.connect(airsWindow.onPupilCenterSet)
        self.irisViewer.pupilBorderSet.connect(airsWindow.onPupilBorderSet)
        self.irisViewer.irisCenterSet.connect(airsWindow.onIrisCenterSet)
        self.irisViewer.irisBorderSet.connect(airsWindow.onIrisBorderSet)
        self.normalizeButton.clicked.connect(airsWindow.onNormalizeButtonClicked)
        self.encodeButton.clicked.connect(airsWindow.onEncodeButtonClicked)
        self.segmentButton.clicked.connect(airsWindow.onSegmentButtonClicked)
        self.computeHeatmapButton.clicked.connect(airsWindow.onComputeHeatmapButtonClicked)
        self.showMaskCheckBox.stateChanged['int'].connect(airsWindow.onShowMaskStateChanged)
        self.templateWidthSpinBox.valueChanged['int'].connect(airsWindow.onTemplateWidthSpinBoxValueChanged)
        self.templateHeightSpinBox.valueChanged['int'].connect(airsWindow.onTemplateHeightSpinBoxValueChanged)
        self.runButton.clicked.connect(airsWindow.onRunTestButtonClicked)
        self.stopButton.clicked.connect(airsWindow.onStopTestButtonClicked)
        self.verificationRadioButton.toggled['bool'].connect(airsWindow.onVerificationRadioButtonToggled)
        self.zapRadioButton.toggled['bool'].connect(airsWindow.onZapRadioButtonToggled)
        QtCore.QMetaObject.connectSlotsByName(airsWindow)

    def retranslateUi(self, airsWindow):
        _translate = QtCore.QCoreApplication.translate
        airsWindow.setWindowTitle(_translate("airsWindow", "Automated Iris Recognition System"))
        self.irisImageLabel.setText(_translate("airsWindow", "Iris image - Untitled"))
        self.loadIrisButton.setText(_translate("airsWindow", "..."))
        self.normalizedIrisLabel.setText(_translate("airsWindow", "Normalized iris:"))
        self.heatmapLabel.setText(_translate("airsWindow", "Heatmap:"))
        self.segmentButton.setText(_translate("airsWindow", "Segment"))
        self.normalizeButton.setText(_translate("airsWindow", "Normalize"))
        self.computeHeatmapButton.setText(_translate("airsWindow", "Compute Heatmap"))
        self.encodeButton.setText(_translate("airsWindow", "Encode"))
        self.pupilInfoGroupBox.setTitle(_translate("airsWindow", "Pupil information"))
        self.pupilCenterAbscissaLabel.setText(_translate("airsWindow", "Center X:"))
        self.pupilCenterOrdinateLabel.setText(_translate("airsWindow", "Center Y:"))
        self.pupilBorderAbscissaLabel.setText(_translate("airsWindow", "Border X:"))
        self.pupilBorderOrdinateLabel.setText(_translate("airsWindow", "Border Y:"))
        self.pupilRadiusLabel.setText(_translate("airsWindow", "Radius:"))
        self.irisInfoGroupBox.setTitle(_translate("airsWindow", "Iris information"))
        self.irisCenterAbscissaLabel.setText(_translate("airsWindow", "Center X:"))
        self.irisCenterOrdinateLabel.setText(_translate("airsWindow", "Center Y:"))
        self.irisBorderAbscissaLabel.setText(_translate("airsWindow", "Border X:"))
        self.irisBorderOrdinateLabel.setText(_translate("airsWindow", "Border Y:"))
        self.irisRadiusLabel.setText(_translate("airsWindow", "Radius:"))
        self.segMethodGroupBox.setTitle(_translate("airsWindow", "Segmentation method"))
        self.projIrisRadioButton.setText(_translate("airsWindow", "Project iris segmentation method"))
        self.vasirRadioButton.setText(_translate("airsWindow", "Vasir segmentation method"))
        self.irisProcessingTabWidget.setTabText(self.irisProcessingTabWidget.indexOf(self.irisSegmentationTab), _translate("airsWindow", "Segmentation"))
        self.normTechniqueGroupBox.setTitle(_translate("airsWindow", "Normalization technique"))
        self.concentricRadioButton.setText(_translate("airsWindow", "Concentric pupil and iris"))
        self.nonconcentricRadioButton.setText(_translate("airsWindow", "Non concentric pupil and iris"))
        self.dataMappingGroupBox.setTitle(_translate("airsWindow", "Data mapping information"))
        self.angularResolutionLabel.setText(_translate("airsWindow", "Angular resolution:"))
        self.radialResolutionLabel.setText(_translate("airsWindow", "Radial resolution:"))
        self.noiseInfoGroupBox.setTitle(_translate("airsWindow", "Noise information"))
        self.showMaskCheckBox.setText(_translate("airsWindow", "Show mask"))
        self.irisProcessingTabWidget.setTabText(self.irisProcessingTabWidget.indexOf(self.irisNormalizationTab), _translate("airsWindow", "Normalization"))
        self.encodingTechniqueGroupBox.setTitle(_translate("airsWindow", "Encoding technique"))
        self.daugmanRadioButton.setText(_translate("airsWindow", "Daugman\'s encoding technique (2D Gabor Filters)"))
        self.masekRadioButton.setText(_translate("airsWindow", "Masek\'s encoding technique (LoG Gabor Filters)"))
        self.zernikeCircularRadioButton.setText(_translate("airsWindow", "Zernike Circular Polynomials technique"))
        self.zernikeAnnularRadioButton.setText(_translate("airsWindow", "Zernike Annular Polynomials technique"))
        self.fourierRadioButton.setText(_translate("airsWindow", "Fourier technique"))
        self.irisProcessingTabWidget.setTabText(self.irisProcessingTabWidget.indexOf(self.irisEncodingTab), _translate("airsWindow", "Encoding"))
        self.irisProcessingTabWidget.setTabText(self.irisProcessingTabWidget.indexOf(self.outputTab), _translate("airsWindow", "Output"))
        self.airsOptionsTabWidget.setTabText(self.airsOptionsTabWidget.indexOf(self.processingTab), _translate("airsWindow", "Processing"))
        self.algorithmSelectionGroupBox.setTitle(_translate("airsWindow", "Algorithm selection"))
        self.segmentationGroupBox.setTitle(_translate("airsWindow", "Segmentation"))
        self.projectIrisSegmRadioButton.setText(_translate("airsWindow", "Project iris"))
        self.vasirSegmRadioButton.setText(_translate("airsWindow", "Vasir (NIST)"))
        self.encodingGroupBox.setTitle(_translate("airsWindow", "Encoding"))
        self.projectIrisEncRadioButton.setToolTip(_translate("airsWindow", "Encoding based in 2D Gabor filters"))
        self.projectIrisEncRadioButton.setText(_translate("airsWindow", "Project iris"))
        self.vasirEncRadioButton.setToolTip(_translate("airsWindow", "Encoding based in LoG Gabor filters"))
        self.vasirEncRadioButton.setText(_translate("airsWindow", "Vasir (NIST)"))
        self.zcpEncRadioButton.setToolTip(_translate("airsWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Encoding based in the Zernike Circular Polynomials</span></p></body></html>"))
        self.zcpEncRadioButton.setText(_translate("airsWindow", "ZCP"))
        self.zapEncRadioButton.setToolTip(_translate("airsWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Encoding based in the Zernike Annular Polynomials</span></p></body></html>"))
        self.zapEncRadioButton.setText(_translate("airsWindow", "ZAP"))
        self.fourierEncRadioButton.setText(_translate("airsWindow", "Fourier"))
        self.matchThresholdLabel.setText(_translate("airsWindow", "Threshold:"))
        self.normalizationGroupBox.setTitle(_translate("airsWindow", "Normalization"))
        self.projectIrisNormRadioButton.setToolTip(_translate("airsWindow", "Normalization method that assumes concentric pupil and iris"))
        self.projectIrisNormRadioButton.setText(_translate("airsWindow", "Project iris"))
        self.vasirNormRadioButton.setToolTip(_translate("airsWindow", "Normalization method that assumes non-concentric pupil and iris"))
        self.vasirNormRadioButton.setText(_translate("airsWindow", "Vasir (NIST)"))
        self.originalIrisLabel.setText(_translate("airsWindow", "Original Iris - Untitled"))
        self.originalLoadIrisButton.setText(_translate("airsWindow", "..."))
        self.queryIrisLabel.setText(_translate("airsWindow", "Query Iris - Untitled"))
        self.queryLoadIrisButton.setText(_translate("airsWindow", "..."))
        self.goButton.setText(_translate("airsWindow", "Go!"))
        self.resultLabel.setText(_translate("airsWindow", "?"))
        self.airsOptionsTabWidget.setTabText(self.airsOptionsTabWidget.indexOf(self.matchTab), _translate("airsWindow", "Match"))
        self.encMethodGroupBox.setTitle(_translate("airsWindow", "Encoding methods"))
        self.gaborEncRadioButton.setText(_translate("airsWindow", "2D Gabor Filters"))
        self.logGaborEncRadioButton.setText(_translate("airsWindow", "LoG-Gabor Filters"))
        self.fourEncRadioButton.setText(_translate("airsWindow", "Fourier encoding"))
        self.zcpRadioButton.setText(_translate("airsWindow", "ZCP"))
        self.zapRadioButton.setText(_translate("airsWindow", "ZAP"))
        self.kComboBox.setToolTip(_translate("airsWindow", "Amount of basis functions"))
        self.kComboBox.setItemText(0, _translate("airsWindow", "16"))
        self.kComboBox.setItemText(1, _translate("airsWindow", "32"))
        self.kComboBox.setItemText(2, _translate("airsWindow", "48"))
        self.kLabel.setText(_translate("airsWindow", "K:"))
        self.testKindGroupBox.setTitle(_translate("airsWindow", "Test kind"))
        self.verificationRadioButton.setText(_translate("airsWindow", "Verification"))
        self.identificationRadioButton.setText(_translate("airsWindow", "Identification"))
        self.thresholdLabel.setText(_translate("airsWindow", "Threshold:"))
        self.databaseGroupBox.setTitle(_translate("airsWindow", "Database"))
        self.upolRadioButton.setText(_translate("airsWindow", "UPOL"))
        self.casia1RadioButton.setText(_translate("airsWindow", "CASIA 1"))
        self.mmuRadioButton.setText(_translate("airsWindow", "MMU"))
        self.ubirisRadioButton.setText(_translate("airsWindow", "UBIRIS"))
        self.useMaskCheckBox.setText(_translate("airsWindow", "Use mask"))
        self.runButton.setText(_translate("airsWindow", "Run"))
        self.stopButton.setText(_translate("airsWindow", "Stop"))
        self.resultsGroupBox.setTitle(_translate("airsWindow", "Results"))
        self.airsOptionsTabWidget.setTabText(self.airsOptionsTabWidget.indexOf(self.testsTab), _translate("airsWindow", "Tests"))
        self.menuFile.setTitle(_translate("airsWindow", "File"))
        self.menuAdvanced.setTitle(_translate("airsWindow", "Advanced"))
        self.menuHelp.setTitle(_translate("airsWindow", "Help"))
        self.actionQuit.setText(_translate("airsWindow", "Quit"))
        self.actionConfiguration.setText(_translate("airsWindow", "Configuration"))
        self.actionAbout.setText(_translate("airsWindow", "About..."))
        self.actionHelp.setText(_translate("airsWindow", "Help"))
        self.actionHelp.setShortcut(_translate("airsWindow", "F1"))

from ui.image_viewer_widget import ImageViewerWidget
from ui.iris_viewer_widget import IrisViewerWidget
